name: continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: onisk/katahellocicd:linttest

      - name: Run linter
        run: docker run onisk/katahellocicd:linttest deno lint

      - name: Run tests
        run: docker run --rm onisk/katahellocicd:linttest deno test
        
      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: onisk/katahellocicd:latest
